# for local development
version: '3.7'
services:
  devel:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - './src:/app/src'
    command: /bin/sh -c "yarn serve"
  
  export:
    build:
      context: .
      target: 'develop-stage'
    volumes:
    - './dist:/app/export'
    - './src:/app/src'
    command: /bin/sh -c "yarn build && cp -R ./dist/* ./export/"

  prod:
    build:
      context: .
      target: 'production-stage'
    ports:
    - '80:80'
